#pragma once

// Auto-updated by CMake when project VERSION changes.
// Do not edit this file by hand.

#define MYOWNQL_VERSION_MAJOR 0
#define MYOWNQL_VERSION_MINOR 1
#define MYOWNQL_VERSION_PATCH 0
#define MYOWNQL_VERSION "0.1.0"
